GUIDE: dict[str, dict] = {
    "curbside_trash": {
        "display_name": "Curbside trash bag",
        "agency": "DSNY (Sanitation)",
        "channel": "311 online / 311 phone / NYC 311 app",
        "link": "https://portal.311.nyc.gov/article/?kanumber=KA-01788",
        "service_type": "Missed Trash, Recycling, or Compost Collection",
        "instructions": "File a Missed Collection report with DSNY. You'll need the address and your regular collection day.",
    },
    "bulk_item": {
        "display_name": "Bulk item (mattress, furniture, appliance)",
        "agency": "DSNY",
        "channel": "311",
        "link": "https://portal.311.nyc.gov/article/?kanumber=KA-01969",
        "service_type": "Bulk Item Disposal",
        "instructions": "If it's your item, schedule a bulk pickup with DSNY via 311 and leave it curbside on your collection day. If it's not yours (someone dumped it), file as Illegal Dumping instead.",
    },
    "illegal_dumping": {
        "display_name": "Illegal dumping",
        "agency": "DSNY Enforcement",
        "channel": "311",
        "link": "https://portal.311.nyc.gov/article/?kanumber=KA-02097",
        "service_type": "Illegal Dumping",
        "instructions": "File an Illegal Dumping report with DSNY. Your photo helps — save it. Include address, time of day, and any details about who or what dumped it.",
    },
    "overflowing_basket": {
        "display_name": "Overflowing litter basket",
        "agency": "DSNY",
        "channel": "311",
        "link": "https://portal.311.nyc.gov/article/?kanumber=KA-02143",
        "service_type": "Litter Basket Complaint or Request",
        "instructions": "File a Litter Basket Complaint via 311. Include cross streets or the nearest address.",
    },
    "park_trash": {
        "display_name": "Trash in a park",
        "agency": "NYC Parks",
        "channel": "311",
        "link": "https://portal.311.nyc.gov/article/?kanumber=KA-01060",
        "service_type": "Park Maintenance Complaint",
        "instructions": "File a Park Maintenance Complaint via 311. Include the park name and a landmark (entrance, playground, specific path).",
    },
    "dog_waste": {
        "display_name": "Dog waste on sidewalk",
        "agency": "DSNY / DOHMH",
        "channel": "311",
        "link": "https://portal.311.nyc.gov/article/?kanumber=KA-02247",
        "service_type": "Dog or Animal Waste",
        "instructions": "File Dog or Animal Waste via 311. Enforcement of a specific violation usually requires witnessing the owner, but recurring issues at a location can still be reported and routed to enforcement.",
    },
    "dead_animal": {
        "display_name": "Dead animal",
        "agency": "DOHMH (small) / NYPD (large) / NYC Parks (in parks)",
        "channel": "311",
        "link": "https://portal.311.nyc.gov/article/?kanumber=KA-02245",
        "service_type": "Dead Animal on Public Property",
        "instructions": "File Dead Animal via 311 for removal. For a pet with a tag, call 311 directly so they can route to the right agency.",
    },
    "broken_sidewalk": {
        "display_name": "Cracked or broken sidewalk",
        "agency": "NYC DOT",
        "channel": "311",
        "link": "https://portal.311.nyc.gov/article/?kanumber=KA-02235",
        "service_type": "Broken Sidewalk",
        "instructions": "File Broken Sidewalk with DOT via 311. Note: in NYC the property owner usually repairs sidewalks, but DOT can inspect and notify the owner, especially for tripping hazards.",
    },
    "pothole": {
        "display_name": "Pothole",
        "agency": "NYC DOT",
        "channel": "311",
        "link": "https://portal.311.nyc.gov/article/?kanumber=KA-01093",
        "service_type": "Pothole or Cave-In on Street",
        "instructions": "File Pothole via 311. Provide the street address and note which lane or direction of travel.",
    },
    "damaged_sign": {
        "display_name": "Fallen or damaged traffic sign",
        "agency": "NYC DOT",
        "channel": "311",
        "link": "https://portal.311.nyc.gov/article/?kanumber=KA-01063",
        "service_type": "Street Sign Complaint",
        "instructions": "File a Street Sign Complaint via 311. Include the intersection and which direction the sign was facing.",
    },
    "broken_streetlight": {
        "display_name": "Broken or out streetlight",
        "agency": "NYC DOT (Street Lighting)",
        "channel": "311",
        "link": "https://portal.311.nyc.gov/article/?kanumber=KA-02463",
        "service_type": "Street Light Complaint",
        "instructions": "File a Street Light Complaint via 311. If the pole has a visible ID number, include it — speeds up the fix.",
    },
    "graffiti": {
        "display_name": "Graffiti",
        "agency": "Graffiti-Free NYC (DSNY) / NYPD",
        "channel": "DSNY / 311",
        "link": "https://www.nyc.gov/site/dsny/what-we-do/cleaning/graffiti.page",
        "service_type": "Graffiti Removal",
        "instructions": "If you own the property, you can request free cleanup through Graffiti-Free NYC (DSNY). Otherwise file Graffiti via 311 to get it routed.",
    },
    "tree_damage": {
        "display_name": "Damaged tree or fallen branch",
        "agency": "NYC Parks (Forestry)",
        "channel": "311",
        "link": "https://portal.311.nyc.gov/article/?kanumber=KA-02138",
        "service_type": "Fallen Tree or Branch",
        "instructions": "File Fallen Tree or Branch via 311 (routed to NYC Parks Forestry). For life-safety hazards (tree on power lines, blocking a street, on top of a vehicle), call 911, not 311.",
    },
    "abandoned_vehicle": {
        "display_name": "Abandoned vehicle",
        "agency": "NYPD (via 311)",
        "channel": "311",
        "link": "https://portal.311.nyc.gov/article/?kanumber=KA-02130",
        "service_type": "Abandoned Vehicle",
        "instructions": "File Abandoned Vehicle via 311. Include make, model, color, license plate (if any), and how long it's been there.",
    },
    "other": {
        "display_name": "Unknown / other",
        "agency": "General 311",
        "channel": "311 online or phone",
        "link": "https://portal.311.nyc.gov/",
        "service_type": "General inquiry",
        "instructions": "Use the 311 online portal or call 311 and describe the issue — they'll route. If you're not sure where it fits, this is the safest option.",
    },
}


def get_guide(category: str) -> dict:
    return GUIDE.get(category, GUIDE["other"])
